on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Create Release
        run: gh release create ${{github.ref}} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.ISSUES_TOKEN }}